from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from pathlib import Path

from acquisition.presets import get_preset


REPO_ROOT = Path(__file__).resolve().parents[2]
GENERATED_ARDUINO_SKETCH_DIR = REPO_ROOT / "data" / "generated_arduino_sketches"
DEFAULT_FALLBACK_RATE_HZ = 120


@dataclass(frozen=True, slots=True)
class GeneratedSketchArtifact:
    sketch_dir: Path
    sketch_path: Path
    sample_rate_hz: int
    sample_period_us: int
    analog_ports: tuple[str, ...]


def _timestamp_tag() -> str:
    return datetime.now().strftime("%Y_%m_%d_%H_%M_%S")


def _sanitize_comment_text(text: str) -> str:
    return text.replace("\n", " ").replace("\r", " ").strip()


def _signal_rate_hz(signal_configuration) -> int:
    preset = get_preset(signal_configuration.preset_name)
    return preset.default_sample_rate_hz or preset.default_cycle_rate_hz or DEFAULT_FALLBACK_RATE_HZ


def determine_generated_sample_rate_hz(signal_configurations) -> int:
    rates = [_signal_rate_hz(signal_configuration) for signal_configuration in signal_configurations]
    return max(rates, default=DEFAULT_FALLBACK_RATE_HZ)


def determine_generated_acquisition_class(signal_configurations) -> str:
    sample_rate_hz = determine_generated_sample_rate_hz(signal_configurations)
    return "CONT_HIGH" if sample_rate_hz > 500 else "CONT_MED"


def render_generated_analog_capture_sketch(signal_configurations, baud_rate: int) -> str:
    sample_rate_hz = determine_generated_sample_rate_hz(signal_configurations)
    sample_period_us = max(1, round(1_000_000 / sample_rate_hz))
    analog_ports = tuple(signal_configuration.analog_port for signal_configuration in signal_configurations)
    acquisition_class = determine_generated_acquisition_class(signal_configurations)

    selected_signal_comments = "\n".join(
        f"//   {signal_configuration.analog_port} -> {_sanitize_comment_text(signal_configuration.name)}"
        f" [{signal_configuration.preset_name}]"
        for signal_configuration in signal_configurations
    )
    selected_ports_csv = ",".join(analog_ports)
    fields_csv = ",".join(("t_ms", *analog_ports))
    analog_input_constants = ", ".join(analog_ports)

    return f"""// Generated by the Biomedical Instrumentation Lab GUI.
//
// This sketch is generated from the currently selected GUI signals.
// Highest selected preset rate: {sample_rate_hz} Hz.
// Selected signals:
{selected_signal_comments}
//
// Shared protocol packets:
//   META,lab,GUI_SELECTED_SIGNALS
//   META,acq_class,{acquisition_class}
//   META,rate_hz,{sample_rate_hz}
//   META,fields,{fields_csv}
//   DATA,{fields_csv}

const unsigned long BAUD_RATE = {baud_rate};
const unsigned long SAMPLE_RATE_HZ = {sample_rate_hz};
const unsigned long SAMPLE_PERIOD_US = {sample_period_us};

const int ANALOG_INPUT_PINS[] = {{{analog_input_constants}}};
const int ANALOG_INPUT_COUNT = sizeof(ANALOG_INPUT_PINS) / sizeof(ANALOG_INPUT_PINS[0]);

unsigned long nextSampleTimeUs = 0;

void writeMetadata() {{
  Serial.println("META,lab,GUI_SELECTED_SIGNALS");
  Serial.println("META,acq_class,{acquisition_class}");
  Serial.println("META,rate_hz,{sample_rate_hz}");
  Serial.println("META,fields,{fields_csv}");
  Serial.println("META,selected_ports,{selected_ports_csv}");
}}

void setup() {{
  Serial.begin(BAUD_RATE);

  while (!Serial && millis() < 3000) {{
  }}

  writeMetadata();
  nextSampleTimeUs = micros();
}}

void loop() {{
  const unsigned long nowUs = micros();

  if ((long)(nowUs - nextSampleTimeUs) < 0) {{
    return;
  }}

  nextSampleTimeUs += SAMPLE_PERIOD_US;

  const unsigned long tMs = millis();

  Serial.print("DATA,");
  Serial.print(tMs);

  for (int index = 0; index < ANALOG_INPUT_COUNT; ++index) {{
    Serial.print(",");
    Serial.print(analogRead(ANALOG_INPUT_PINS[index]));
  }}

  Serial.println();
}}
"""


def create_generated_analog_capture_sketch(signal_configurations, baud_rate: int) -> GeneratedSketchArtifact:
    timestamp = _timestamp_tag()
    sketch_name = f"generated_arduino_code_{timestamp}"
    sketch_dir = GENERATED_ARDUINO_SKETCH_DIR / sketch_name
    suffix = 1
    while sketch_dir.exists():
        sketch_name = f"generated_arduino_code_{timestamp}_{suffix}"
        sketch_dir = GENERATED_ARDUINO_SKETCH_DIR / sketch_name
        suffix += 1

    sketch_dir.mkdir(parents=True, exist_ok=False)
    sketch_path = sketch_dir / f"{sketch_name}.ino"
    sketch_path.write_text(
        render_generated_analog_capture_sketch(signal_configurations, baud_rate),
        encoding="utf-8",
    )

    sample_rate_hz = determine_generated_sample_rate_hz(signal_configurations)
    sample_period_us = max(1, round(1_000_000 / sample_rate_hz))
    analog_ports = tuple(signal_configuration.analog_port for signal_configuration in signal_configurations)

    return GeneratedSketchArtifact(
        sketch_dir=sketch_dir,
        sketch_path=sketch_path,
        sample_rate_hz=sample_rate_hz,
        sample_period_us=sample_period_us,
        analog_ports=analog_ports,
    )
